import type { EditorComponent, ExportFormat } from './types'

function indent(level: number): string {
  return '  '.repeat(level)
}

function propsToReactAttrs(props: Record<string, unknown>): string {
  return Object.entries(props)
    .filter(([key, value]) => {
      if (key === 'children') return false
      if (value === undefined || value === null || value === '') return false
      if (typeof value === 'boolean' && !value) return false
      return true
    })
    .map(([key, value]) => {
      if (typeof value === 'string') return `${key}="${value}"`
      if (typeof value === 'boolean') return key
      if (typeof value === 'number') return `${key}={${value}}`
      return `${key}={${JSON.stringify(value)}}`
    })
    .join(' ')
}

function propsToVueAttrs(props: Record<string, unknown>): string {
  return Object.entries(props)
    .filter(([key, value]) => {
      if (key === 'children') return false
      if (value === undefined || value === null || value === '') return false
      if (typeof value === 'boolean' && !value) return false
      return true
    })
    .map(([key, value]) => {
      if (typeof value === 'boolean') return `:${key}="true"`
      if (typeof value === 'number') return `:${key}="${value}"`
      return `${key}="${value}"`
    })
    .join(' ')
}

function propsToHTMLAttrs(props: Record<string, unknown>): string {
  return Object.entries(props)
    .filter(([key, value]) => {
      if (key === 'children') return false
      if (key === 'variant' || key === 'size' || key === 'isLoading' || key === 'isFullWidth') return false
      if (value === undefined || value === null || value === '') return false
      if (typeof value === 'boolean' && !value) return false
      return true
    })
    .map(([key, value]) => {
      if (typeof value === 'boolean') return key
      return `${key}="${value}"`
    })
    .join(' ')
}

function componentToReact(component: EditorComponent, level: number): string {
  const attrs = propsToReactAttrs(component.props)
  const children = component.props.children as string
  const hasChildren = children || component.children?.length

  if (!hasChildren) {
    return `${indent(level)}<${component.type}${attrs ? ' ' + attrs : ''} />`
  }

  let output = `${indent(level)}<${component.type}${attrs ? ' ' + attrs : ''}>`
  if (typeof children === 'string') {
    output += `${children}</${component.type}>`
  } else if (component.children?.length) {
    output += '\n'
    for (const child of component.children) {
      output += componentToReact(child, level + 1) + '\n'
    }
    output += `${indent(level)}</${component.type}>`
  } else {
    output += `</${component.type}>`
  }

  return output
}

function componentToVue(component: EditorComponent, level: number): string {
  const attrs = propsToVueAttrs(component.props)
  const children = component.props.children as string
  const hasChildren = children || component.children?.length

  if (!hasChildren) {
    return `${indent(level)}<${component.type}${attrs ? ' ' + attrs : ''} />`
  }

  let output = `${indent(level)}<${component.type}${attrs ? ' ' + attrs : ''}>`
  if (typeof children === 'string') {
    output += `${children}</${component.type}>`
  } else if (component.children?.length) {
    output += '\n'
    for (const child of component.children) {
      output += componentToVue(child, level + 1) + '\n'
    }
    output += `${indent(level)}</${component.type}>`
  } else {
    output += `</${component.type}>`
  }

  return output
}

function componentToHTML(component: EditorComponent, level: number): string {
  const tagMap: Record<string, string> = {
    Button: 'button',
    Input: 'input',
    Card: 'div',
    Icon: 'span'
  }
  const tag = tagMap[component.type] || 'div'
  const attrs = propsToHTMLAttrs(component.props)
  const children = component.props.children as string

  if (component.type === 'Input') {
    return `${indent(level)}<${tag}${attrs ? ' ' + attrs : ''} class="input" />`
  }

  let output = `${indent(level)}<${tag}${attrs ? ' ' + attrs : ''} class="${component.type.toLowerCase()}">`
  if (typeof children === 'string') {
    output += `${children}</${tag}>`
  } else if (component.children?.length) {
    output += '\n'
    for (const child of component.children) {
      output += componentToHTML(child, level + 1) + '\n'
    }
    output += `${indent(level)}</${tag}>`
  } else {
    output += `</${tag}>`
  }

  return output
}

export function exportCode(components: EditorComponent[], format: ExportFormat): string {
  const converter = {
    react: componentToReact,
    vue: componentToVue,
    html: componentToHTML
  }[format]

  const imports = {
    react: "import { Button, Input, Card, Icon } from '@mylib/components'\n\n",
    vue: '<template>\n',
    html: '<!-- Generated by Design Editor -->\n'
  }

  let output = imports[format]

  if (format === 'vue') {
    for (const component of components) {
      output += converter(component, 1) + '\n'
    }
    output += '</template>'
  } else if (format === 'react') {
    output += 'export function Component() {\n  return (\n'
    output += '<>\n'
    for (const component of components) {
      output += converter(component, 1) + '\n'
    }
    output += '</>\n  )\n}'
  } else {
    for (const component of components) {
      output += converter(component, 0) + '\n'
    }
  }

  return output
}
