import type { ThemeDefinition } from '../types'

export const darkTheme: ThemeDefinition = {
  id: 'dark',
  name: 'Dark',
  description: 'Dark mode theme',
  mode: 'dark',
  tokens: [
    { name: 'bg-primary', value: '#111827' },
    { name: 'bg-secondary', value: '#1F2937' },
    { name: 'bg-tertiary', value: '#374151' },
    { name: 'text-primary', value: '#F9FAFB' },
    { name: 'text-secondary', value: '#D1D5DB' },
    { name: 'text-tertiary', value: '#6B7280' },
    { name: 'text-inverse', value: '#111827' },
    { name: 'brand-primary', value: '#60A5FA' },
    { name: 'brand-primary-hover', value: '#93C5FD' },
    { name: 'brand-primary-active', value: '#3B82F6' },
    { name: 'brand-primary-light', value: '#1E3A8A' },
    { name: 'border-default', value: '#374151' },
    { name: 'border-hover', value: '#4B5563' },
    { name: 'border-focus', value: '#60A5FA' },
    { name: 'state-success', value: '#34D399' },
    { name: 'state-warning', value: '#FBBF24' },
    { name: 'state-error', value: '#F87171' },
    { name: 'card-bg', value: '#1F2937' },
    { name: 'card-border', value: '#374151' },
    { name: 'input-bg', value: '#1F2937' },
    { name: 'input-bg-disabled', value: '#111827' },
    { name: 'input-border', value: '#374151' },
    { name: 'input-border-hover', value: '#4B5563' },
    { name: 'input-border-focus', value: '#60A5FA' },
    { name: 'input-text', value: '#F9FAFB' },
    { name: 'input-text-placeholder', value: '#6B7280' },
    { name: 'button-bg-primary', value: '#60A5FA' },
    { name: 'button-bg-primary-hover', value: '#93C5FD' },
    { name: 'button-bg-primary-active', value: '#3B82F6' },
    { name: 'button-bg-secondary', value: '#374151' },
    { name: 'button-bg-secondary-hover', value: '#4B5563' },
    { name: 'button-text-primary', value: '#111827' },
    { name: 'button-text-secondary', value: '#F9FAFB' },
  ]
}
