import type { ThemeDefinition } from '../types'

export const lightTheme: ThemeDefinition = {
  id: 'light',
  name: 'Light',
  description: 'Default light theme',
  mode: 'light',
  tokens: [
    { name: 'bg-primary', value: '#FFFFFF' },
    { name: 'bg-secondary', value: '#F9FAFB' },
    { name: 'bg-tertiary', value: '#F3F4F6' },
    { name: 'text-primary', value: '#111827' },
    { name: 'text-secondary', value: '#4B5563' },
    { name: 'text-tertiary', value: '#9CA3AF' },
    { name: 'text-inverse', value: '#FFFFFF' },
    { name: 'brand-primary', value: '#3B82F6' },
    { name: 'brand-primary-hover', value: '#2563EB' },
    { name: 'brand-primary-active', value: '#1D4ED8' },
    { name: 'brand-primary-light', value: '#DBEAFE' },
    { name: 'border-default', value: '#E5E7EB' },
    { name: 'border-hover', value: '#D1D5DB' },
    { name: 'border-focus', value: '#3B82F6' },
    { name: 'state-success', value: '#22C55E' },
    { name: 'state-warning', value: '#EAB308' },
    { name: 'state-error', value: '#EF4444' },
    { name: 'card-bg', value: '#FFFFFF' },
    { name: 'card-border', value: '#E5E7EB' },
    { name: 'input-bg', value: '#FFFFFF' },
    { name: 'input-bg-disabled', value: '#F9FAFB' },
    { name: 'input-border', value: '#E5E7EB' },
    { name: 'input-border-hover', value: '#D1D5DB' },
    { name: 'input-border-focus', value: '#3B82F6' },
    { name: 'input-text', value: '#111827' },
    { name: 'input-text-placeholder', value: '#9CA3AF' },
    { name: 'button-bg-primary', value: '#3B82F6' },
    { name: 'button-bg-primary-hover', value: '#2563EB' },
    { name: 'button-bg-primary-active', value: '#1D4ED8' },
    { name: 'button-bg-secondary', value: '#F3F4F6' },
    { name: 'button-bg-secondary-hover', value: '#E5E7EB' },
    { name: 'button-text-primary', value: '#FFFFFF' },
    { name: 'button-text-secondary', value: '#111827' },
  ]
}
