import fs from 'fs-extra'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const svgDir = path.join(__dirname, '..', 'src', 'icons', 'svg')
const outputDir = path.join(__dirname, '..', 'src', 'icons')

const pascalCase = (str) =>
  str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')

const toCamelCase = (str) => {
  const pascal = pascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

function parseSVG(svgContent) {
  const viewBoxMatch = svgContent.match(/viewBox="([^"]+)"/)
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24'

  const fillMatch = svgContent.match(/fill="([^"]+)"/)
  const strokeMatch = svgContent.match(/stroke="([^"]+)"/)
  const strokeWidthMatch = svgContent.match(/stroke-width="([^"]+)"/)
  const strokeLinecapMatch = svgContent.match(/stroke-linecap="([^"]+)"/)
  const strokeLinejoinMatch = svgContent.match(/stroke-linejoin="([^"]+)"/)

  const innerContent = svgContent
    .replace(/<\/?svg[^>]*>/g, '')
    .replace(/fill="[^"]*"/g, '')
    .trim()

  return {
    viewBox,
    fill: fillMatch ? fillMatch[1] : 'none',
    stroke: strokeMatch ? strokeMatch[1] : 'currentColor',
    strokeWidth: strokeWidthMatch ? strokeWidthMatch[1] : '2',
    strokeLinecap: strokeLinecapMatch ? strokeLinecapMatch[1] : 'round',
    strokeLinejoin: strokeLinejoinMatch ? strokeLinejoinMatch[1] : 'round',
    innerContent
  }
}

async function generateIcons() {
  await fs.ensureDir(svgDir)

  const svgFiles = (await fs.pathExists(svgDir))
    ? (await fs.readdir(svgDir)).filter((f) => f.endsWith('.svg'))
    : []

  if (svgFiles.length === 0) {
    console.log('No SVG files found in src/icons/svg/. Place SVG files there and re-run.')
    console.log('Creating example SVG file...')

    const exampleSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="M20 6L9 17l-5-5"/>
</svg>`

    await fs.writeFile(path.join(svgDir, 'check.svg'), exampleSvg)
    console.log('Created example: src/icons/svg/check.svg')
    return
  }

  const icons = []

  for (const file of svgFiles) {
    const name = path.basename(file, '.svg')
    const content = await fs.readFile(path.join(svgDir, file), 'utf-8')
    const parsed = parseSVG(content)

    icons.push({
      name,
      componentName: pascalCase(name) + 'Icon',
      ...parsed
    })
  }

  let indexContent = `// Auto-generated by generate-icons.js\n// Do not edit manually\n\n`
  let registryContent = `import type { IconDefinition } from './types'\n\n`

  for (const icon of icons) {
    indexContent += `export { ${icon.componentName} } from './generated/${icon.componentName}'\n`
    registryContent += `export const ${toCamelCase(icon.name)}: IconDefinition = {\n`
    registryContent += `  name: '${icon.name}',\n`
    registryContent += `  category: 'custom',\n`
    registryContent += `  description: '${icon.name} icon',\n`
    registryContent += `  svg: {\n`
    registryContent += `    viewBox: '${icon.viewBox}',\n`
    registryContent += `    fill: '${icon.fill}',\n`
    registryContent += `    stroke: '${icon.stroke}',\n`
    registryContent += `    strokeWidth: ${icon.strokeWidth},\n`
    registryContent += `    strokeLinecap: '${icon.strokeLinecap}' as const,\n`
    registryContent += `    strokeLinejoin: '${icon.strokeLinejoin}' as const,\n`
    registryContent += `  }\n`
    registryContent += `}\n\n`
  }

  const generatedDir = path.join(outputDir, 'generated')
  await fs.ensureDir(generatedDir)

  for (const icon of icons) {
    const componentContent = `import { Icon } from '../Icon'\nimport type { IconProps } from '../types'\n\nexport const ${icon.componentName} = (props: Omit<IconProps, 'name'>) => (\n  <Icon name="${icon.name}" {...props} />\n)\n`
    await fs.writeFile(
      path.join(generatedDir, `${icon.componentName}.tsx`),
      componentContent
    )
  }

  await fs.writeFile(path.join(generatedDir, 'index.ts'), indexContent)
  await fs.writeFile(path.join(outputDir, 'generated-registry.ts'), registryContent)

  console.log(`Generated ${icons.length} icon components in src/icons/generated/`)
}

generateIcons().catch(console.error)
